### ISSUE TITLE
cleanup repo

### ISSUE THREAD

**Issue by Fovty** [caas-team/new-pykube#10]
## Issue
Repo content is currently inconsistent with actual repo status

### Problem to solve

search for all wrong references:

- [x]  pykube-ng -> pykube  - **decision needed** - response from namespace owner of [pykube on PyP](https://pypi.org/project/pykube/) is curently pending
- [x] **Deprecated Elements**: Identify all deprecated references and ensure they are either updated or removed.

### Proposal

Replace old information with updated
### Who can address the issue

Everyone, but solving the PyPI package namespace first is necessary

**Comment by Fovty** [comment]
From the last PR discussion:

> > In order to keep track, here are the remaining references, right?
> > 
> > * `README.md`
> > * `docs/index.rst`
> > * `docs/users.rst`
> > * `docs/write-an-operator.rst`
> > * `pykube/config.py`
> > * `pykube/http.py`
> > * `pykube/test_config.py`
> > * `pykube/test_http.py`
> 
> Pretty much. Just keep in mind that it's `docs/howtos/write-an-operator.rst` to avoid confusion.

**Comment by JTaeuber** [comment]
Information should be up to date for now.
